# quotes.py
weekly_quotes = [
    "Week 1: Success is the sum of small efforts repeated day in and day out. — Robert Collier",
    "Week 2: Don’t watch the clock; do what it does. Keep going. — Sam Levenson",
    "Week 3: Quality means doing it right when no one is looking. — Henry Ford",
    "Week 4: Your attitude, not your aptitude, will determine your altitude. — Zig Ziglar",
    "Week 5: The secret of getting ahead is getting started. — Mark Twain",
    "Week 6: Believe you can and you're halfway there. — Theodore Roosevelt",
    "Week 7: Make each day your masterpiece. — John Wooden",
    "Week 8: Start where you are. Use what you have. Do what you can. — Arthur Ashe",
    "Week 9: Success is not final, failure is not fatal: It is the courage to continue that counts. — Winston Churchill",
    "Week 10: If opportunity doesn't knock, build a door. — Milton Berle",
    "Week 11: The only way to do great work is to love what you do. — Steve Jobs",
    "Week 12: Action is the foundational key to all success. — Pablo Picasso",
    "Week 13: Don’t count the days, make the days count. — Muhammad Ali",
    "Week 14: Whether you think you can or think you can’t, you’re right. — Henry Ford",
    "Week 15: Strive not to be a success, but rather to be of value. — Albert Einstein",
    "Week 16: Great things are done by a series of small things brought together. — Vincent Van Gogh",
    "Week 17: Perseverance is not a long race; it is many short races one after the other. — Walter Elliot",
    "Week 18: You miss 100% of the shots you don’t take. — Wayne Gretzky",
    "Week 19: Dream big and dare to fail. — Norman Vaughan",
    "Week 20: What lies behind us and what lies before us are tiny matters compared to what lies within us. — Ralph Waldo Emerson",
    "Week 21: Happiness is not something ready made. It comes from your own actions. — Dalai Lama",
    "Week 22: The harder I work, the luckier I get. — Samuel Goldwyn",
    "Week 23: Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau",
    "Week 24: Challenges are what make life interesting. Overcoming them is what makes life meaningful. — Joshua Marine",
    "Week 25: It always seems impossible until it's done. — Nelson Mandela",
    "Week 26: Keep your face always toward the sunshine—and shadows will fall behind you. — Walt Whitman",
    "Week 27: Do what you can, with what you have, where you are. — Theodore Roosevelt",
    "Week 28: Don’t wish it were easier. Wish you were better. — Jim Rohn",
    "Week 29: Well done is better than well said. — Benjamin Franklin",
    "Week 30: Either you run the day or the day runs you. — Jim Rohn",
    "Week 31: Be so good they can’t ignore you. — Steve Martin",
    "Week 32: I am not a product of my circumstances. I am a product of my decisions. — Stephen Covey",
    "Week 33: You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
    "Week 34: Live as if you were to die tomorrow. Learn as if you were to live forever. — Mahatma Gandhi",
    "Week 35: The future depends on what you do today. — Mahatma Gandhi",
    "Week 36: If you can dream it, you can do it. — Walt Disney",
    "Week 37: There are no shortcuts to any place worth going. — Beverly Sills",
    "Week 38: In the middle of difficulty lies opportunity. — Albert Einstein",
    "Week 39: Motivation is what gets you started. Habit is what keeps you going. — Jim Ryun",
    "Week 40: Success is walking from failure to failure with no loss of enthusiasm. — Winston Churchill",
    "Week 41: Do not wait to strike till the iron is hot; but make it hot by striking. — William Butler Yeats",
    "Week 42: The only limit to our realization of tomorrow is our doubts of today. — Franklin D. Roosevelt",
    "Week 43: Work hard in silence, let your success be your noise. — Frank Ocean",
    "Week 44: Courage doesn’t always roar. Sometimes courage is the quiet voice at the end of the day saying ‘I will try again tomorrow.’ — Mary Anne Radmacher",
    "Week 45: You don’t need to see the whole staircase, just take the first step. — Martin Luther King Jr.",
    "Week 46: Success is not the key to happiness. Happiness is the key to success. — Albert Schweitzer",
    "Week 47: Do not be afraid to give up the good to go for the great. — John D. Rockefeller",
    "Week 48: If you want to achieve greatness stop asking for permission. — Anonymous",
    "Week 49: Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. — Roy T. Bennett",
    "Week 50: The way to get started is to quit talking and begin doing. — Walt Disney",
    "Week 51: Push yourself, because no one else is going to do it for you. — Anonymous",
    "Week 52: Success is liking yourself, liking what you do, and liking how you do it. — Maya Angelou"
]
